
package org.micomupu.ot.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrdenService", targetNamespace = "http://service.ot.micomupu.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrdenService {


    /**
     * 
     * @return
     *     returns java.util.List<org.micomupu.ot.service.Trabajo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarOrdenTrabajo", targetNamespace = "http://service.ot.micomupu.org/", className = "org.micomupu.ot.service.ConsultarOrdenTrabajo")
    @ResponseWrapper(localName = "consultarOrdenTrabajoResponse", targetNamespace = "http://service.ot.micomupu.org/", className = "org.micomupu.ot.service.ConsultarOrdenTrabajoResponse")
    public List<Trabajo> consultarOrdenTrabajo();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.micomupu.ot.service.Trabajo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresarOrden", targetNamespace = "http://service.ot.micomupu.org/", className = "org.micomupu.ot.service.IngresarOrden")
    @ResponseWrapper(localName = "ingresarOrdenResponse", targetNamespace = "http://service.ot.micomupu.org/", className = "org.micomupu.ot.service.IngresarOrdenResponse")
    public Trabajo ingresarOrden(
        @WebParam(name = "arg0", targetNamespace = "")
        Trabajo arg0);

}
